name: Update JavaDoc

on:
  push:

jobs:
  update-javadoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          # Make sure we can execute.
          chmod +x ./gradlew

          # Build JavaDoc.
          ./gradlew javadoc

      - name: Checkout Web Branch
        uses: actions/checkout@v4
        with:
          repository: xqzpop7/VoxelStash
          ref: web
          path: web

      - name: Copy JavaDoc Static Site Content
        run: |
          # Clean previous JavaDoc.
          rm -rf web/*
          
          # Copy new JavaDoc.
          cp -r build/docs/javadoc/* web/

      - name: Commit And Push To Web Branch
        working-directory: web
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add *
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit!"
          else
            git commit -m "Updated VoxelStash JavaDoc!"
            git push origin web
          fi


